language: ruby
dist: xenial
services: docker
cache: bundler

notifications:
  email: project@bendler-net.de

before_install:
  - rm Gemfile.lock || true
  - gem update --system
  - gem update bundler
  - gem --version
  - bundle --version

branches:
  only:
    - master
    - release

stages:
  - name: build
  - name: test
  - name: deploy
    if: branch = release

script:
  - bundler install && bundler update
  - bundle exec rake $CHECK

jobs:
  include:
    - stage: build
      env: PUPPET_VERSION="~> 6.0"
      install: bundler install && bundler update
      script: bundle exec rake test
      after_success: skip

    - stage: test
      env: BEAKER_set=default BEAKER_debug=1
      install: bundler install && bundler update
      script: bundle exec rake beaker
      after_success: skip

#    - stage: test
#      env: BEAKER_set=debian9-64 BEAKER_debug=1
#      install: bundler install && bundler update
#      script: bundle exec rake beaker
#      after_success: skip

#    - stage: test
#      env: BEAKER_set=ubuntu1810-64 BEAKER_debug=1
#      install: bundler install && bundler update
#      script: bundle exec rake beaker
#      after_success: skip

    - stage: deploy
      install: skip
      script: skip
      after_success: skip
      deploy:
        provider: puppetforge
        user: thbe
        password:
          secure: gfdVXZYvGgcz3ylYlXQLmFnJVJlLjAmwM3ehN37+e6QxmWxq4ObtVZKSCGfvw3xuNYRolKjNfZs6rcPKo0jg+zAKbgckAZFo14YyNdRPTEIr5LMNLScu3wiQSYGaZ8Wo+Ednluz3uU6CNg+3bm1GeaS7uxLM8vCNxqGFQHecgS7FuNevmVB6J5cq0G+eZ9SSRDkVkv+ex/ffWWLJKSa8AK4L0UD6mWTK4l+smeJ6PElqlpSzhYsyJY9BRR8+y6oOfjm5gAZyX5BNG2ocrjva5lxdzIDNzqfsISj4+gUkltcL//9gRN7xG5nvK5uemRKYTXgpNTfXDcl7+br8xTSy9tllWe0e3Iya9CZlPPJD6VWuPShBVlrQ5yIjIPUzQv7Ls2q8SqtHnl2S8Wum6IN1Mr+YAKvMMEnEPKVmlWmE9EWTOZHjs9P6S98P0c632T1BCJzv1xNnhWfZOF9wM+zD/k2ZIQStmV85ufyxEqzNCJ+UO6jtgivnf9CP0kx4jSUqGv3FdFyWqL0CbCUkrvRXWHu5PbKsEP/pNTdkdsPNJ79fU9JZ4Azakpucsy8vdRBRgmgfxkLJ2z68NOI0LVbe5iWgDIqHRFbx20eS2mf5cxIswtzI3uAfngC648JbWmud6VdBEBY01TCu7454LL+Kj/NaTl0ZMT63dy82v3rvQvw=
      on:
        tags: true
        all_branches: true
